### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ggpasqualino** [gVirtu/scenic-snake#2]
We (@codecurious-bln) are planning some workshops in Elixir and we have encountered your tutorial https://blog.usejournal.com/elixir-scenic-snake-game-b8616b1d7ee0
We really liked it and we are considering using it for our first workshop. 
However, according to https://choosealicense.com/no-permission/ 
>  Unless you include a license that specifies otherwise, nobody else can copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation. 

we are not able to do so unless the repo has a license that allows us to do it.

Would you be so kind and consider adding one of the [licenses](https://choosealicense.com/licenses/) to this project?

**Comment by gVirtu** [comment]
Absolutely! Please feel free to use it.
I am adding the MIT License to the project.

**Comment by ggpasqualino** [comment]
Awesome! Thank you 💜
